observations<-read.table("X_train.txt",sep="",header=FALSE)
print("A")
variables<-read.table("../features.txt", sep="", header=FALSE)
print("B")
subjsByObs<-read.table("subject_train.txt",sep="", header=FALSE)
print("C")
variableNames<-character(0)
print("D")
variableNames<-as.character(variables[,2])
print("E")
for(i in 1:length(variableNames)){
        
        #transform      
        variableNames[i]<-gsub("[,][1][^0-9]","Walking", variableNames[i])
        variableNames[i]<-gsub("[,][2][^0-9]","WalkingUp", variableNames[i])
        variableNames[i]<-gsub("[,][3][^0-9]","WalkingDown", variableNames[i])
        variableNames[i]<-gsub("[,][4][^0-9]","Sitting", variableNames[i])
        variableNames[i]<-gsub("[,][5][^0-9]","Standing", variableNames[i])
        variableNames[i]<-gsub("[,][6][^0-9]","Lying", variableNames[i])
        variableNames[i]<-gsub("Jerk","Thrust", variableNames[i])
        variableNames[i]<-gsub("entropy","Decline", variableNames[i])
        variableNames[i]<-gsub("arCoeff","Coeff", variableNames[i])
        variableNames[i]<-gsub("^f","", variableNames[i])
        variableNames[i]<-gsub("^t","", variableNames[i])
        variableNames[i]<-gsub("Body","", variableNames[i])
        variableNames[i]<-gsub("Acc","Acceleration", variableNames[i])
        variableNames[i]<-gsub("GravityAcceleration","GravitationalPull",variableNames[i])
        variableNames[i]<-gsub("GravityAcceleration","GravitationalPull",variableNames[i])
        variableNames[i]<-gsub("GyroThrust","RotationalVelocity",variableNames[i])
        variableNames[i]<-gsub("Gyro","Rotational",variableNames[i])
        variableNames[i]<-gsub("mean","Mean", variableNames[i])
        variableNames[i]<-gsub("correlation","Corr", variableNames[i])
        variableNames[i]<-gsub("Mag","Magnitude", variableNames[i])
        variableNames[i]<-gsub("mad","Median", variableNames[i])
        variableNames[i]<-gsub("bandsEnergy","EnergyInRange", variableNames[i])
        variableNames[i]<-gsub("angle","AngleBetweenVectors", variableNames[i])
        variableNames[i]<-gsub("sma","Magnitude", variableNames[i])
        variableNames[i]<-gsub("maxInds","MaxMagnitude", variableNames[i])
        variableNames[i]<-gsub("iqr","InterQuartileRange", variableNames[i])
        variableNames[i]<-gsub("AngleBetweenVectors","DirectionalChange", variableNames[i])
        variableNames[i]<-gsub("AccelerationThrust","Acceleration", variableNames[i])
        variableNames[i]<-gsub("std","StdDev", variableNames[i])
        variableNames[i]<-gsub("energy","Energy", variableNames[i])
        variableNames[i]<-gsub("max","Max", variableNames[i])
        variableNames[i]<-gsub("min","Min", variableNames[i])
        variableNames[i]<-gsub("-","",variableNames[i])  
        variableNames[i]<-gsub("[(]","",variableNames[i])
        variableNames[i]<-gsub("[)]","",variableNames[i])
        variableNames[i]<-gsub("WalkingUpWalkingUp","WalkingUp",variableNames[i])
        variableNames[i]<-gsub("DirectionalChangetAccelerationMean,gravityMean","DirectionalChangeInThrustRelativeToGravityMean",variableNames[i])
        variableNames[i]<-gsub("DirectionalChangetRotationalVelocityMean,gravityMean","DirectionalChangeThrustRotationalVelocityMeanRelativeToGravity",variableNames[i])
        variableNames[i]<-gsub(",gravity","RelativeToGravity",variableNames[i])
        variableNames[i]<-gsub("DirectionalChangeRotationalMeanRelativeToGravityMean","DirectionalChangetRotationalRelativeToGravityMean",variableNames[i])
}

write.table(variableNames,"variableNames.txt", sep=" ", quote=FALSE)




